# /wordpress-docker/docker-compose.yml
---
version: '3.3'
services:
  db:
    container_name: 'wordpress-db'
    image: 'mysql:5.7'
    volumes:
      - 'wp-mysql-db:/var/lib/mysql'
    ports:
      - 18766:3306
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
  wordpress:
    container_name: 'wordpress'
    user: $UID
    depends_on:
      - db
    image: 'wordpress:latest'
    ports:
      - '80:80'
    environment:
      WORDPRESS_DB_HOST: 'db:3306'
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - "./src:/var/www/html/wp-content/plugins/my-first-wp-plugin"
volumes:
  wp-mysql-db: